package facade;

public enum ItemType {
    BOOTSOFSPEED,
    ENERGYBOOSTER,
    RECIPEBOOTSOFTRAVEL,
    BLADESOFATTACK,
    CHAINMAIL,
    BELTOFSTRENGTH,
    GLOVESOFHASTE,
    RINGOFREGEN,
    WINDLACE,
    ARCANEBOOTS,
    BOOTSOFTRAVEL,
    PHASEBOOTS,
    POWERTREADS,
    TRANQUILBOOTS
}
